### ISSUE TITLE
broken image bij geplaatste tracker als student niet is ingelogd geweest

### ISSUE THREAD

**Issue by hermanvand** [SURFnet/learning-analytics#102]
Als docent maak ik een cursus aan en plaats ik op de homepage twee dingen:
1. de /button
2. een /track van joined - course

Een student die hier voor het eerst komt en NOG NIET bij de test.la-experiment.surfnet.nl server is ingelogd geweest krijgt dan van beiden images een broken images

Nadat de student wel is ingelogd geweest, ziet hij niet meer de broken images

De allereerste keer is juist erg belangrijk omdat dan de /button getoond kan worden, waarmee de student naar de toestemmignsverklaring wordt verwezen om voor de eerste keer in te loggen.

graag fixen voro release 17 aug.

**Comment by rpkamp** [comment]
Weet je zeker dat het hier gaat om ingelogd geweest zijn? Het SSL certificaat van de test server is namelijk self signed en zolang je niet op de pagina geweest bent en het SSL certificaat niet goedgekeurd hebt zal hij inderdaad weigeren om plaatjes van het domein te downloaden en zie je inderdaad een broken image.
Als ik eerst de LA pagina bezoek en het self-signed SSL certificaat goedkeur, _niet_ inlog en dan direct weer naar jouw voorbeeldpagina ga doen de plaatjes het wel namelijk gewoon.

Op productie zit een geldig SSL certificaat dus die zal dat probleem niet hebben.
