### ISSUE TITLE
javascript van het antwoord op een formatieve toets geeft een fout, terwijl de html versie het wel doet

### ISSUE THREAD

**Issue by hermanvand** [SURFnet/learning-analytics#104]
In de code staan:

&lt;!-- test javascript -->
&lt;script>la=[];la.push(['track',3,'answered','question',3,'quiz 1','week 1','geen test 1',{id:'7e2c146f-4775-410f-8f6e-ee06f7850cde'}]);</script>
&lt;script src="https://test.la-experiment.surfnet.nl/js/tracker.js" async defer></script>

en

&lt;!-- test html -->
&lt;img src="https://test.la-experiment.surfnet.nl/track?recipe=3&amp;verb=answered&amp;object=question&amp;course=3&amp;label=quiz 1&amp;week=week 1&amp;subject=geen test 1&amp;params[id]=7e2c146f-4775-410f-8f6e-ee06f7850cde&amp;">

---
Deze code staat op: http://145.100.181.60/versie12/2.html

---
De javascript geeft een '400 bad request' terug. Met deze content:
{"code":400,"message":"Validation Failed","errors":{"errors":["This form should not contain extra fields
."],"children":{"recipe":[],"verb":[],"object":[],"course":[],"referrer":[],"label":[],"params":{"children"
:{"id":[]}}}}}

---
Het lijkt er dus op dat 'week' en 'subject' niet mee mogen in de post

**Comment by rpkamp** [comment]
Je test pagina POST de data naar de productie omgeving en niet naar de test omgeving als je dit via javascript doet.

Om naar de correcte URL te posten moet je de code aanpassen naar:

```javascript
la=[];
la.push('setUrl', 'https://test.la-experiment.surfnet.nl/track');
la.push(['track',3,'answered','question',3,'quiz 1','week 1','geen test 1',{id:'7e2c146f-4775-410f-8f6e-ee06f7850cde'}]);
```

als je dit niet doet worden alle tracks naar `https://la-experiment.surfnet.nl/track` gePOST.

Als je de URL naar de juiste URL POST zou het wel goed moeten gaan.
