### ISSUE TITLE
verbeteren afhandeling van 'foute' xapi statements.

### ISSUE THREAD

**Issue by hermanvand** [SURFnet/learning-analytics#111]
dit komt voor op twee plaatsen

1. als er een verb/object combinatie wordt gebruikt door een docent die niet mogelijk is (bijvoorbeeld joined-article), dan komt deze activiteit wel in de 'tijdelijke' opslag van het la-experiment. Vervolgens stopt de nachtelijke update bij het verwerken van deze 'foute' activiteit en worden activiteiten die daarna in de opslag staan niet meer doorgezet naar de LRS.

2. Als er een verb/object combinatie in de lrs komt die niet aan het recept voldoet, dan wordt bij het aggregeren van data en het maken van de fim dit statement niet meegenomen, en dan stopt dit proces ook, waardoor de fim niet compleet is

**Comment by pablothedude** [comment]
Hier een aanpassing voor gedaan zodat deze fouten worden opgevangen en er een notice wordt opgegooid waarna er daarna gewoon verder wordt gegaan.

**Comment by hermanvand** [comment]
kan ik niet testen, maar process script wel gedraaid op test en het werkt.
