### ISSUE TITLE
ipv. xapi recept een object maken

### ISSUE THREAD

**Issue by hermanvand** [SURFnet/learning-analytics#112]
De redenering is als volgt:

De tracking code van een pixel/image op een pagina is goed door docenten te gebruiken. Alleen stellen docenten (en wij ook) vragen bij de accuratie van de meetgegevens, want een pixel op een pagina wil nog niet zeggen dat een bepaalde actie op diezelfde pagina ook door de student is uitgevoerd. Zelfs als er maar een enkele link of video op die ene pagina staat.
We kunnen bewijzen dat meetgegevens accuraat kunnen zijn, zie de examples op http://145.100.181.60/example.html. Dat vergt echter gebruik van javascript op de pagina. Daar zitten twee nadelen aan verbonden: 1. niet iedere LMS/bron staat toe dat we javascipt gebruiken en de 2e uitdaging is om javascript gebruiksvriendelijk te maken voor docenten.
Maar wat gaan we nu doen?

A. Gaan we heel veel effort steken in het gebruiksvriendelijk maken van de javascript, zodat de docent zo min mogelijk hoeft te doen. Denk dan aan het minimaliseren van de code en eigen objecten introduceren, voor bijvoorbeeld het embedden van een youtube filmpje, net als youtube 'embed' bij het afspelen van een video.

Of B. Hebben we nu voldoende aangetoont dat het experiment werkt, maar moeten we de conclusie maken dat er een combinatie van mensen nodig is, docenten + ict-ers/developers om javascript trackers bij materiaal te plaatsen. We kunnen dan dus de code gaan uitleggen omdat de gebruikers meer tech georienteerd zijn. Zoals Youtube bijvoorbeeld hier doet voor zijn player: https://developers.google.com/youtube/iframe_api_reference. Zo kunnen wij ook een reference maken voor het gebruiken van trackers. Net als piwik, zie https://developer.piwik.org/guides/media-analytics/setup

**Comment by MKodde** [comment]
@hermanvand, is het mogelijk om uit te leggen hoe ik het genoemde voorbeeld kan bekijken op: http://145.100.181.60/example.html ?

**Comment by hermanvand** [comment]
Die url is verouderd, ik heb de demo pagina's wat opgeschoond nadat ik dit schreef. De nieuwe url van dit specifieke voorbeeld is: http://145.100.181.60/demo/3.html

**Comment by pablothedude** [comment]
Hiervoor een toevoeging gemaakt bij stap 2 (`Video`/`Accessed`) waarbij een template te zien is voor een youtube implementatie.

**Comment by hermanvand** [comment]
Deze toevoeging vraagt nog om 3 aanpassingen, zie:

![afbeelding](https://user-images.githubusercontent.com/1597455/33549049-91f7a430-d8e9-11e7-866b-61ed22d388c2.png)

1. vormgeving: 'Video integratie' mag als blok onder het blok 'javascript integratie'. De zin 'Voor expert integratie, ....' mag onderaan.

2. In de code mist het volgende:
`

<script src="https://la-experiment.surfnet.nl/js/tracker.js" async defer></script>
<script type="text/javascript" src="http://www.youtube.com/player_api"> </script>


<div id="player"></div>
</div>`

3. In het la.push statement mist het course_id (tussen 'video' & 'hoi')

**Comment by pablothedude** [comment]
# Vreemd dat je layout zo afwijkt t.o.v. die van mij. Welke browser gebruik je, dan kan ik even verder  kijken waar mogelijk een probleem zit?
# De toevoeging in de code is gedaan
# De aanpassing met de missende courseid is gedaan.

**Comment by hermanvand** [comment]
Oh, dat screenshot ziet er beter uit. Ik heb volgens mij getest met firefox. En als student log ik meestal in met chrome.

**Comment by hermanvand** [comment]
2 en 3 zijn opgelost. Alleen de layout is nog niet zoals het screenshot hierboven

**Comment by pablothedude** [comment]
Dit is opgelost, het is denk ik gekomen door een merge die een aantal aanpassingen terug had gezet. Dit zou nu opgelost moeten zijn.

**Comment by hermanvand** [comment]
klopt, dit werkt.
