### ISSUE TITLE
[system] deployment met docker

### ISSUE THREAD

**Issue by hermanvand** [SURFnet/learning-analytics#113]
aanpassen repro voor deployment met docker, zodat SURFsara makkelijker beheer en releasemangement kan doen.

- clean dockerfile (zonder capistrano)
- taggen van releases, docker file op basis van tags

**Comment by pablothedude** [comment]
Voorgesteld om eens  naar gitlab te kijken. In afwachting van bevindingen.

**Comment by pablothedude** [comment]
Docker staat klaar en een verzoek is gedaan aan Ander uit om een PR klaar te zetten met de aanpassingen die nodig waren om alles op productie voor elkaar te krijgen.

**Comment by hermanvand** [comment]
dit is vandaag afgerond
