### ISSUE TITLE
toestemmingsverklaring in het engels

### ISSUE THREAD

**Issue by hermanvand** [SURFnet/learning-analytics#114]
de vertaling is er al. op de nl toestemmingsverklaring kunnen we een link maken naar deze engelse versie.

**Comment by pablothedude** [comment]
Hoi Herman, waar kan ik de tekst voor de engelse versie vinden?

**Comment by hermanvand** [comment]
bij deze

[ENG-DEFtoestemmingsverklaring LA experiment - EN.docx](https://github.com/SURFnet/learning-analytics/files/1417643/ENG-DEFtoestemmingsverklaring.LA.experiment.-.EN.docx)

**Comment by pablothedude** [comment]
Bedankt, het viel me overigens nog wel op dat het mogelijk was om per instituut nog additionele veiligheidsmaatregelen op te geven. Dit is alleen in het Nederlands en dit blokje heb ik daarom niet meegenomen in de Engelse versie.

**Comment by pablothedude** [comment]
Dit staat klaar. Hierbij was trouwens nog besloten dat de additionele veiligheidsmaatregelen per instituut in vreemde talen voor nu buiten beschouwing kon worden gelaten.

**Comment by hermanvand** [comment]
fixed
