### ISSUE TITLE
kunnen we een overzicht van bestaande trackers laten zien

### ISSUE THREAD

**Issue by hermanvand** [SURFnet/learning-analytics#115]
en niet alleen de laatste 10.

de simpele oplossing is een 'more' knopje, zodat je er meer kan laten zien. En een sorteer knopje, zodat je kunt sorteren op datum en/of naam.

**Comment by pablothedude** [comment]
Herman, zou je misschien aan kunnen geven om welk overzicht dit gaat? We dachten dat dit zou gaan om de inzendingen op het recipe tabblad. Alleen kunnen dit er meer dan 10 zijn. Alvast mijn dank.

**Comment by pablothedude** [comment]
Herman, zou je misschien aan kunnen geven om welk overzicht dit gaat? We dachten dat dit zou gaan om de inzendingen op het recipe tabblad. Alleen kunnen dit er meer dan 10 zijn. Alvast mijn dank.

**Comment by hermanvand** [comment]
Dat klopt, het gaat om stap 3 in het recipe blad. Ik heb zelf de limiet van 10 niet getest, maar hoorde van docenten die meer recepten hadden gemaakt dat ze niet allemaal hier zichtbaar zijn.

Als dat niet zo is, dan kunnen we volstaan met een sortering op deze lijst. Zodat je makkelijk kunt zien welk als laatste is toegevoegd (sorteer op datum) of makkelijk een bepaalde tracker kunt vinden. (sorteer op naam)

**Comment by pablothedude** [comment]
Hiervoor een aanpassing gedaan waarbij het mogelijk is om op de kolommen te sorteren. Wat me overigens wel op viel is dat nu alle requests in dit lijstje staan en misschien zal er daarom op termijn nog iets van paginering moeten komen.

**Comment by hermanvand** [comment]
fixed

**Comment by hermanvand** [comment]
Deze moet ik nog even openen. Het filter op 'recipe' lijkt er uit te zijn. Ik ging kijken onder ' monitor studievoortgang' of de joined course daar ook zou staan. Ik zag echter dat alle activiteiten van alle recepten daar stonden. Dat hoeft niet, ik had alleen het recept wat ik bekijk verwacht.

**Comment by pablothedude** [comment]
Hoi Herman, dit heeft nooit zo gewerkt en op deze pagina was altijd al alle data zichtbaar van een bepaalde course. Als je kijkt in de usage tabel dan mist hier ook een kolom om op recipe te kunnen sorteren. Ik wil voorstellen hier even een apart ticket voor aan te maken.

`'usage' => $this->getDoctrine()->getRepository(Usage::class)->findBy(['course' => $courseId])`

**Comment by hermanvand** [comment]
hier maken we een nieuw issue van
