### ISSUE TITLE
full information matrix: na klikken op 'ik doe niet meer mee' wel de persoon blijven tellen.

### ISSUE THREAD

**Issue by hermanvand** [SURFnet/learning-analytics#14]

**Comment by Tjeerd** [comment]
Data wordt nu geanonimiseerd bij afmelden, hierdoor veranderen de statistieken dus niet en is een persoon niet meer (gemakkelijk) te herleiden.

Let wel: in de LRS is de data nog wel beschikbaar. Data kan hier niet "verwijderd" worden, maar moet gemarkeerd worden als "voided". Dit laatste moet nog worden geïmplementeerd.
