### ISSUE TITLE
interface: een selectie maken van visualisaties

### ISSUE THREAD

**Issue by hermanvand** [SURFnet/learning-analytics#16]
nu zijn er veel op 1 pagina

**Comment by Tjeerd** [comment]
* Joined Course altijd laten zien
* Filter voor graphs met/zonder data; standaard alleen graphs met data laten zien

**Comment by Tjeerd** [comment]
Er is nu een knop beschikbaar waarmee grafieken zonder "positieve" (Yes) metingen kunnen worden verborgen. Standaard staat deze aan.
