### ISSUE TITLE
interface: optie bij visualisaties om bij iedere grafiek aan te geven of meerdere events samengevoegd kunnen worden

### ISSUE THREAD

**Issue by hermanvand** [SURFnet/learning-analytics#17]
collapse per label, doen we nu automatisch bij grafiek a. Dat zou je ook als optie willen kunnen bij andere grafieken: als je vraagt 'heeft iemand iets bekeken'. Dan kan het voldoende zijn dat iemand het een keer heeft bekeken. Dan hoef je niet te tellen hoevaak hij het heeft bekeken. (de 'unit of observation')

**Comment by Tjeerd** [comment]
* Toevoegen histogram across verbs and objects

**Comment by Tjeerd** [comment]
Ter bevestiging: er wordt een staafdiagram toegevoegd waar alle object, verb en labels combinaties zichtbaar worden.
