### ISSUE TITLE
[RECEPTEN] recept uitbreiden met cijfers

### ISSUE THREAD

**Issue by hermanvand** [SURFnet/learning-analytics#18]
grafiek d, werkt nu over meerdere assessment, maar niet over de cijfers. De grades zitten in de context van één assesment. Daarmee kunnen we het recept uitbreiden in de toekomst

**Comment by rpkamp** [comment]
Een recept bestaat atijd uit object / verb / label, dat blijft altijd bestaan.

Voor toetsen voegen we hier een aantal velden aan toe. Te weten:

Bij selectie van
 - Object: Question
 - Verb: Answer

klapt er een extra veld uit bij het aanmaken van een recept:

 - Toets: <string>
 - Vraag: <string>
 - Antwoord: <string>
 - Success: <radio>
 - Score: <number>

Voor in xAPI:
Context (nieuwe IRI)
 - toets
 - vraag
 - antwoord

Result:
 - success
 - score [min, max, raw] -> (sum(raw) / sum(max) ~> cijfer)
 - (indien nodig voor xAPI): completion (default to true)
