### ISSUE TITLE
security: moeten we niet https gebruiken?

### ISSUE THREAD

**Issue by hermanvand** [SURFnet/learning-analytics#19]

**Comment by hermanvand** [comment]
toch weer naar de sprint. want om te koppelen aan surfconext productie is dit nodig, kom ik vandaag achter...

het certificaat is aangevraagd en ik zal dat op de server en apache installeren. Hopelijk behoeft dit geen wijzigingen aan de applicatie.

**Comment by Tjeerd** [comment]
De code is, daar waar nodig, aangepast om altijd met https te werken.
