### ISSUE TITLE
tracking: de tracking achter een <img> tag hangen 

### ISSUE THREAD

**Issue by hermanvand** [SURFnet/learning-analytics#23]
de js code mag nl. niet altijd gebruikt worden. Bijvoorbeeld niet in de SURFnet wiki en ook niet in de VU blackboard omgeving. Maar externe images mogen wel geladen worden in beide systemen.

**Dit haalt een hoge drempel weg!**

**Comment by Tjeerd** [comment]
Let wel dat deze variant minder flexibel is omdat hiermee het tracken van clicks e.d. erg lastig wordt.

**Comment by Tjeerd** [comment]
E.e.a. geimplementeerd in #28

**Comment by hermanvand** [comment]
Top tjeerd! ik ga het morgen proberen in de surfnet wiki. Zeker is dit minder flexible, maar dit is de basis. Men kan dan javascript gebruiken als ze meer willen. Dit gaan heel veel mensen fijn vinden :-)

**Comment by Tjeerd** [comment]
Binary issue?

**Comment by Tjeerd** [comment]
Ja, binary issue, fixed.
