### ISSUE TITLE
[RECEPTEN] 'volgt de student zijn eigen voortgang' kunnen we uit onze eigen site halen

### ISSUE THREAD

**Issue by hermanvand** [SURFnet/learning-analytics#24]
idee:
- als iemand een cursus maakt, wordt automatisch voor die cursus een 2e cursus gemaakt onder het kopje 'volgt de student zijn eigen voortgang'
- vervolgens loggen wij de activiteiten die de student op onze experiment omgeving uitvoert en maken dit zichtbaar hieronder

merk op: dit lukt misschien niet voor eind oktober. Eerst de rest!

**Comment by pablothedude** [comment]
Hiervoor heb ik een aparte activity/verb combinatie voor aangemaakt (`Analytics`/`Accessed`). Deze wordt getriggered op het moment dat een recipe pagina wordt geopend. Dus er wordt per course/recipe een tracking pixel ingeschoten.

**Comment by hermanvand** [comment]
kan ik ook niet testen, vanwege /track probleem, zie #94 
Zie wel bij de student dat de / track poging wordt gedaan, maar die komt dus niet aan.

**Comment by pablothedude** [comment]
Hiervoor in afwachting op #94 zodat dit te testen is.

**Comment by hermanvand** [comment]
Ik kan nu wel testen, maar de tracker lijkt niet goed te zijn. ALs ik naar de voortgang kijk, dan wordt deze tracker getriggerd, met een undefined recipe:

https://test.la-experiment.surfnet.nl/admin/course/3/recipe/undefined?order=timestamp&direction=desc

dat geeft een 500 error, de leeractiviteit wordt dus niet opgeslagen

**Comment by pablothedude** [comment]
Als ik kijk naar ene studenten pagina wordt de call voor de tracking gewoon gedaan. De ongeldige url leek te komen door een andere bug. Dit kwam doordat er een call werd gedaan om de tabel op te halen met de resultaten onder de recepten ook al was deze tabel niet zichtbaar. Hiervoor een fix klaar gezet zodat deze call dan niet wordt gedaan.

**Comment by hermanvand** [comment]
Bijna goed, denk ik, ik zie de tracker nu statements naar de lrs gooien. 

Er zit nog een foutje in het recipe. Deze verwijst naar 4, maar moet zijn 2

**Comment by hermanvand** [comment]
Deze tracked nu het nieuwe recept. Ik zie de trackers verschijnen in de lrs.

MAAR, de trackers van de studenten worden nu bij het inlezen vanuit de lrs in fim gezien als trackers van de docent. Want ik zie geen statistieken update, maar ik zie activiteit in het lijst op de 'recept' pagina. 

Dit geldt nu voor ALLE activiteiten die ik als student uitvoer. Die komen in de ' recept'  lijst en niet bij de visualisaties!

**Comment by pablothedude** [comment]
De interacties in het lijstje bij de recepten zijn interacties die uit de 'usage' tabel komen en dit staat verder los van de interacties in de 'fim' tabel. Deze worden namelijk in de 'usage' tabel gezet omdat interacties van een leraar niet worden getracked en het dus voor een leraar mogelijk wordt om interacties te testen zonder dat ze in de 'fim' tabel worden gezet.

De interacties in de 'usage' tabel zijn interacties binnen één Course en worden niet uitgesplitst per Recipe zoals je mogelijkerwijs zou (mogen) verwachten. Misschien kan hier een nieuw issue voor worden aangemaakt als je dit uitgesplitst zou willen hebben.

Daarom denk ik dat de betreffende visualisaties onder een ander Recipe te vinden moeten zijn. Omdat ik eerder een migratie heb klaar gezet om onder alle recipes een 'Analytics/Accessed' tracker aan te maken zijn er denk ik verkeerde interacties ingeschoten. Deze tracker zou alleen onder 'Monitoring studievoortgang' aangemaakt moeten worden en niet onder alle vier recipes,

Ik heb een fix klaar staan maar wilde eerst even voor de zekerheid even verifieren of ze wel onder de visualisatie van een andere recipe te vinden zijn?

**Comment by pablothedude** [comment]
Dit even samen bekeken in Utrecht en dit is goed bevonden.

**Comment by pablothedude** [comment]
Dit even samen bekeken in Utrecht en dit is goed bevonden.

**Comment by hermanvand** [comment]
werkt nu op produktie bij surfsara
