### ISSUE TITLE
tracking: cross domain scripting mogelijk maken

### ISSUE THREAD

**Issue by hermanvand** [SURFnet/learning-analytics#26]
aangepast
- track.js: daarin moest de url naar het la-experiment opgenomen worden.
- app.php: daarin is de 'OPTIONS' even snel verwerkt om het werkend te maken en staan pointers om het netjes te implementeren. Zie:

<?php

use Symfony\Component\HttpFoundation\Request;

/**
 * @var Composer\Autoload\ClassLoader
 */
$loader = require __DIR__ . '/../app/autoload.php';
include_once __DIR__ . '/../var/bootstrap.php.cache';

$kernel = new AppKernel('prod', false);
$kernel->loadClassCache();

$request = Request::createFromGlobals();

// 'OPTIONS' should be handled with bundle: https://github.com/nelmio/NelmioCorsBundle
// - for now rewrite options to post
$flag=0;
if ($request->server->get('REQUEST_METHOD') == "OPTIONS") {
	$flag=1;
	$request->server->set('REQUEST_METHOD', 'POST');
}

$response = $kernel->handle($request);

// set additional headers
// - override status OK
// - allow cross site request: https://www.nczonline.net/blog/2010/05/25/cross-domain-ajax-with-cross-origin-resource-sharing/
if ($flag) {
	$response->setStatusCode('200', 'OK');
	$response->headers->set('Access-Control-Allow-Origin', '*');
	$response->headers->set('Access-Control-Allow-Headers', 'Content-Type');
	$response->headers->set('Access-Control-Allow-Methods', 'POST');
}

$response->send();
$kernel->terminate($request, $response);

**Comment by Tjeerd** [comment]
Ik heb een bundle toegevoegd en geconfigureerd welke de CORS headers correct set.
