### ISSUE TITLE
lrs: de lrs wordt niet gevuld vanuit de client met de cron jobs

### ISSUE THREAD

**Issue by hermanvand** [SURFnet/learning-analytics#27]
het lijkt erop dat dit komt omdat er iedere keer een nieuwe user is

**Comment by Tjeerd** [comment]
Ook dit leek een CORS issue te zijn met het delen van cookies. Even afwachten of de stats nu beter gevuld worden.

**Comment by hermanvand** [comment]
ik heb een gebruiker op mijn demo site gehad :-) Morgen even verder testen, maar het lijkt nu door te komen, thanx!
