### ISSUE TITLE
[BEVEILIGING] lrs: kunnen we voor verschillende instellingen, verschillende bakjes maken

### ISSUE THREAD

**Issue by hermanvand** [SURFnet/learning-analytics#29]

**Comment by rpkamp** [comment]
Dit kan opzich wel, maar het aanmaken van een LRS is lijkt een handmatige actie te zijn in Learning Locker. Ik kan tenminste geen endpoints in de API van learning locker vinden om een LRS aan te maken.

De workflow zou dan zijn in Learning Locker een nieuwe LRS aan te maken, de username en password voor de client uit Learning Locker over te nemen en in te vullen bij het aanmaken van een instelling in Learning Analytics.

Daarnaast zijn courses op dit moment ook niet gekoppeld aan een instelling, dus bij binnenkomst van een statement is niet te herleiden in welk bakje dit terecht zou moeten komen, dus daar zouden nog software aanpassingen voor gedaan moeten worden.

**Comment by hermanvand** [comment]
Klopt. De LRS aanmaken is een actie in Learning Locker. Nu is er één LRS, In Learning Analytics krijg je straks een username en wachtwoord voor iedere LRS, per instelling.

btw: de instelling zou te herleiden moeten zijn via de eigenaar van de course. We kunnen een attribuut uit SURFconext hiervoor nemen, genaamd homeorganization: https://wiki.surfnet.nl/display/surfconextdev/Attributen+in+SURFconext#AttributeninSURFconext-sHOHomeorganization

**Comment by hermanvand** [comment]
Surfconext moet dit attribuut leveren, Herman vraag dit na

**Comment by hermanvand** [comment]
Voor het opslaan van statements in de LRS willen we graag verschillende 'bakjes' per instelling maken. Het proces daarbij is als volgt:
- Bij het intake gesprek bij een instelling achterhaalt SURFnet de naam van de instelling die gebruikt wordt voor het 'bakje'
- Op basis van deze naam maakt SURFsara (of SURFnet) een 'bakje' aan op de LRS en geeft daarbij credentials voor toegang vanuit de app.
- Deze credentials worden in de applicatie ingevoerd en daar wordt de toegang voor de instelling getest door Ibuildings (of SURFnet).
- Bij het technisch gesprek bij een instelling logt een nieuwe docent in, die wordt vervolgens gepromoot tot admin door SURFnet (herman) en bij het commando voor de promotie wordt ook de naam van de instelling gegeven, zodat statements in het juiste bakje worden opgeslagen.
