### ISSUE TITLE
Meerdere landingspagina's (per instelling)

### ISSUE THREAD

**Issue by Tjeerd** [SURFnet/learning-analytics#30]
Tekstje + knop "als je hier al eerder bent geweest"

+ Update van tekst

**Comment by Tjeerd** [comment]
@hermanvand: waar vinden we de laatste versie van de "tekst"?

**Comment by Tjeerd** [comment]
E.e.a. is nu zo aangepast dat een url als https://la-experiment.surfnet.nl/{instelling} beschikbaar is en dat afhankelijk van de {instelling} de landingspagina kan worden aangepast. Verdere uitwerking is even afhankelijk van de laatste versie van de "tekst".

**Comment by hermanvand** [comment]
de tekst staat hier opgemaakt: https://www.surf.nl/binaries/content/assets/surf/nl/2016/voorbeeld-toestemmingsverklaring-la-experiment-def.pdf

en dit is hem om te knippen en plakken:

---

Korte introtekst

De [naam instelling] wil zo goed mogelijk bijdragen aan jouw studiesucces en dat van toekomstige
studenten. Daarom wordt dit studiejaar bij het vak [naam van vak] een onderzoek uitgevoerd naar
online studieactiviteiten. Wil je daaraan mee doen? Lees dan de begeleidende tekst en bepaal of je
toestemming geeft. Het staat je vrij om niet mee te doen.

Knop: ‘Ik doe mee’

Uitgebreide tekst

Beste student,

De [naam instelling] wil zo goed mogelijk bijdragen aan jouw studiesucces en dat van toekomstige
studenten. Daarom wordt dit studiejaar bij het vak [naam van vak] een onderzoek uitgevoerd naar
online studieactiviteiten. Wil je daaraan mee doen? Onderstaand staat er meer informatie over het
onderzoek, lees deze informatie en bepaal of je toestemming geeft.

Wat willen we doen en waarom?

• We onderzoeken welke online activiteiten studenten uitvoeren. Op deze wijze ontstaat er inzicht in
online studieactiviteiten.
• We tonen de online studieactiviteiten: docenten en studenten krijgen een overzicht van online
uitgevoerde studentactiviteiten.
• We vragen jouw mening over het tonen van de online studieactiviteiten

Docenten en studenten krijgen door dit onderzoek informatie over:
• Of en op welk moment de student de opdracht(en) uit het vak heeft ingeleverd
• Op welk moment de student de leeractiviteiten heeft uitgevoerd
• Of de student de eigen studievoortgang volgt
• Hoe vaak de student een tussentijdse toets maakt binnen het vak
• Welk lesmateriaal vaak wordt gebruikt door de student

Wat gebeurt er als je meedoet?

Van alle studenten die meedoen aan het onderzoek wordt gedurende de looptijd van het vak [naam
vak] bijgehouden welke studieactiviteiten zij online verrichten. Dit gebeurt alleen voor de
bovenstaande vragen, niet meer en niet minder. Alleen resultaten van deze activiteiten worden
getoond aan de docenten en studenten.

Wil je meedoen? Dan hebben we je toestemming nodig om je persoonsgegevens te gebruiken.
Daarom vragen we je toestemming voor het verzamelen en verwerken van jouw persoonsgegevens
voor dit onderzoek. Dit zijn je mailadres, je voor-­ en achternaam, je studentnummer en de gegevens
die betrekking hebben op jouw online activiteiten die nodig zijn om bovengenoemde
onderzoeksvragen te kunnen beantwoorden. Met deze gegevens identificeren we je, en kunnen we
gericht aan jou en de docenten laten zien wat je online studie-­activiteiten zijn.

Waarvoor gebruiken we je gegevens – en waarvoor zeker niet?
We gebruiken je persoonsgegevens uitsluitend om dit onderzoek uit te voeren. We vinden het heel
belangrijk om zorgvuldig met je persoonsgegevens om te gaan.
Of je deelneemt aan het onderzoek of niet is uitsluitend bekend bij de onderzoekers en de docent van
het vak. We bewaren je gegevens gedurende het onderzoek en drie maanden daarna. Daarna worden
je gegevens volledig geanonimiseerd. Wel bewaren we geaggregeerde gegevens, zodat de
onderbouwing van het onderzoek mogelijk blijft.
In het [is er een privacy reglement op de instelling] vind je de belangrijkste regels over het gebruik van
je persoonsgegevens aan de [naam instelling]. Dit reglement is ook van toepassing op dit onderzoek.

Doe je mee?
Klik dan onderaan dit scherm op “Ik doe mee”. Als je niet mee wil doen, dan hoef je niets te doen. We
benadrukken dat de keuze om wel of niet mee te doen geen invloed heeft op het resultaat van het vak
[naam vak].

Heb je vragen of wil je je later afmelden?
Heb je naar aanleiding van deze informatie vragen? Of besluit je op een later moment dat je niet meer
wilt deelnemen? Dan kun je altijd terecht bij jouw facultaire contactpersoon voor dit onderzoek:
[naam]. Mocht je je later alsnog afmelden, dan zullen we vanaf dat moment je persoonsgegevens niet
langer gebruiken in dit onderzoek.

Met vriendelijke groet,

Knop: ‘Ik doe mee’

**Comment by hermanvand** [comment]
Er staan 4 variabelen in de tekst, dat zijn:
- naam instelling
- naam vak(ken)
- link naar privacy statement instelling
- naam contact persoon

deze gegevens worden nog aangeleverd

**Comment by hermanvand** [comment]
Voor de vu kunnen we maken
- url: https://la-experiment.surfnet.nl/vu
- Vrije Universiteit
- Statistiek 1
- http://www.vu.nl/en/privacy-statement.aspx
- Chris van Klaveren

Voor de default moeten we dan een algemene tekst maken,
- url: https://la-experiment.surfnet.nl/
- instelling
- vak
- [geen link achter de tekst over de privacy verklaring]
- [geen naam van de contactpersoon van de instelling]
