### ISSUE TITLE
Thema & vragen statisch opnemen

### ISSUE THREAD

**Issue by Tjeerd** [SURFnet/learning-analytics#32]

**Comment by Tjeerd** [comment]
@hermanvand: to be sure: wat moeten de statische teksten/vragen ook alweer zijn?

**Comment by hermanvand** [comment]
Thema 1: Inleveren opdrachten

Gekoppelde vragen: 
•	Heeft de student de opdrachten ingeleverd en wanneer?

Thema 2: Monitoring studievoortgang

Gekoppelde vragen: 
•	Volgt de student de eigen voortgang?

Thema 3: Formatieve toetsing

Gekoppelde vragen: 
•	Hoe vaak doet de student een tussentijdse toets?

Thema 4: Gebruik lesmateriaal

Gekoppelde vragen: 
•	Welk materiaal wordt vaak gebruikt?
•	Op welk moment voert de student de leeractiviteit uit?
