### ISSUE TITLE
[BEVEILIGING] encrypten van javascrpt code: /track?2163512983u2enwquiey32iw

### ISSUE THREAD

**Issue by hermanvand** [SURFnet/learning-analytics#35]
dan is er niet meer te rotzooien

**Comment by rpkamp** [comment]
Zoals eerder besproken is dit niet adviseerbaar omdat encrypten/decrypten van data op een gegeven moment een bottleneck binnen het systeem gaat worden. Daarnaast is de vraag in hoeverre je hier echt mensen mee tegen gaat houden, gezien er ook alterntieven zijn om het systeem te "gamen", bijvoorbeeld met selenium test scripts.
