### ISSUE TITLE
[DESIGN] layout van expert integratie verbeteren

### ISSUE THREAD

**Issue by hermanvand** [SURFnet/learning-analytics#36]
het onderste gedeelte komt eenmalig op de pagina
de button wordt steeds herhaald.
--> dat kan dan in twee verschillende vlakken

daarbij moet eigenlijk bij de button ook de class 'btn' weg, want die is niet nodig.

**Comment by hermanvand** [comment]
Ook moet het ophalen van jquery in een apart blokje, dit is nl. optioneel voor als het onderliggende systeem ook al jquery gebruikt. (zoals bij de hu)

**Comment by rpkamp** [comment]
De huidige uitleg voor expert integratie is te complex voor docenten en moet eenvoudiger.

Misschien kunnen we naar een model dat het standaard script alle buttons met een bepaalde css class of data attribuut oppakt?

**Comment by hermanvand** [comment]
Deze week bij Noorderpoort en HS Zuyd problemen gehad met de jquery code. Deze code conflicteerd met al bestaande code. Voor Zuyd heb ik daarom puur javascript code voorgesteld. Dat werkt wel.

In plaats van : 
`<script>
   la = [];
    $('.la-track').on('click', function () {
        var el = $(this);
        la.push(['track', 4, el.data('verb'), el.data('object'), 2, el.data('label')]);
    });
</script>`

Is het geworden : 
`<script>
	la = [];
	var classname = document.getElementsByClassName("la-track");
	var laPush = function() { la.push(['track', 4, this.getAttribute("data-verb"), this.getAttribute("data-object"), 2, this.getAttribute("data-label")]); };
	for (var i = 0; i < classname.length; i++) {
    		classname[i].addEventListener('click', laPush, false);
	}
</script>
`

Dat moet ook in de code maar veranderd worden.

En ja, ik vindt het mooi als een deel daarvan ook in het standaard script komt, maar de la.push() regel is voor ieder gebruik specifiek, dus daar ontkomen we niet aan.

btw: deze code is ook gedemo-ed op: http://145.100.181.60/examples/kliklink.html

**Comment by rpkamp** [comment]
je kan de `la.push()` wel generiek maken als je alle data in het HTML element zet, zoals

```
<span data-toggle="la-track" data-la-payload="{&quot;object&quot;:&quot;question&quot;,&quot;verb&quot;:&quot;answered&quot;,&quot;recipe&quot;:3,&quot;course&quot;:1,&quot;label&quot;:&quot;Toets 1&quot;,&quot;params&quot;:{&quot;id&quot;:&quot;a9d79984-c05f-4cec-a6f5-bec163e925e9&quot;}}">A</span>
```

Dit is een stuk JSON in het attribuut `data-la-payload`. Dat zou de javascript code dan kunnen deserialiseren en vervolgens de losse waarden gebruiken om naar de server te sturen.

Het voordeel is dat de expert integratie dan wel erg makkelijk wordt omdat er in het geheel geen custom javascript meer nodig is, het nadeel is dat die code best wel moeilijk leesbaar is en als er een foutje in zit door verkeerde copy/paste of handmatige aanpassing die niet helemaal correct is (bijvoorbeeld een docent die denkt dat hij wel ergens een " kan toevoegen in de waarde waardoor de volledige HTML kapot gaat), wordt debuggen best lastig.

Alternatief zouden we natuurlijk ook alle waarden uit kunnen schrijven:

```
<span data-toggle="la-track" data-la-object="question" data-la-verb="answered" data-la-recipe="1" data-la-course="4" data-la-label="Toets 1" data-la-params-id="a9d79984-c05f-4cec-a6f5-bec163e925e9">A</span>
```

Dit is al wat makkelijker leesbaar als mens maar het schaalt wat minder makkelijk dan de JSON variant omdat voor iedere param die er bij komt je dit apart af moet vangen en uitlezen in de javascript, terwijl dat met JSON volledig dynamisch is.

**Comment by hermanvand** [comment]
Op de wiki heb ik een uitleg gegeven over het plaatsen van trackers, zie: https://wiki.surfnet.nl/display/laexperiment/Integreren+in+je+leeromgeving 

Daardoor kunnen we nu het volgende doen:
- expert integratie kan helemaal weg, want dat wordt nu uitgelegd.
- een linkje naar de uitleg plaatsen.

Volgens mij zijn we er dan. Het is simpel geworden. En de instellingen zijn nu in ieder geval geholpen. De 'data-payload' optie houden we dan nog even acht de hand.

**Comment by rpkamp** [comment]
Ik had nou juist de expert integratie aangepast zodat er inderdaad geen jQuery meer nodig is, maar iets anders dan die van jou in de zin van dat de code die ik had ook nog werkt als er dynamisch elementen aan de pagina toevoegd worden (denk aan AJAX popup), dat dat dan ook nog werkt.

De code die ik hier voor heb is:
```js
la = [];
window.addEventListener('click', function (event) {
    if ((' ' + event.target.className + ' ').indexOf(' la-track ') === -1) {
        return;
    }

    var el = event.target;
    la.push(['track', {{ recipe.id }}, el.getAttribute('data-verb'), el.getAttribute('data-object'), {{ course.id }}, el.getAttribute('data-label'), el.getAttribute('data-week'), el.getAttribute('data-subject'), {<span class="script-id-placeholder">id: el.getAttribute('data-id')</span>}]);
}, true);
```

Misschien een idee om dit ook op te nemen in de wiki?

**Comment by rpkamp** [comment]
Maar verder lijkt het mij een prima idee om naar de wiki te verwijzen inderdaad, dat zal ik aanpassen.

**Comment by hermanvand** [comment]
De demo en de wiki met uitleg zijn aangepast met bovenstaande code.
