### ISSUE TITLE
[BEVEILIGING] meer doen voor bescherming van privacy

### ISSUE THREAD

**Issue by hermanvand** [SURFnet/learning-analytics#37]
- in de lrs kun je nu lezen wie de actie uitvoert ahv. emailadres. Kunnen we daar pseudonymen van maken?

**Comment by hermanvand** [comment]
Van surfconext kunnen we een versleutelde id krijgen 'edupersontargetedid', zie: https://wiki.surfnet.nl/display/surfconextdev/Attributes+in+SURFconext

Als we die gebruiken, dan kunnen ook andere diensten die van SURFconext gebruik maken de data koppelen aan een persoon, dat lijkt acceptabel

**Comment by rpkamp** [comment]
xAPI staat niet toe een random string te gebruiken voor een gebruiker. Je kan een email adres, de sha1 van een email adres, of een OpenID account gebruiken, maar die passen hier allemaal niet.

Wat we zouden kunnen overwegen is iets als `<edupersontargetedid>@surf-edupersontargetedid.nl` oid als email adres gebruiken. Dan zien we aan het `@surf-edupersontargetedid.nl` dat het geen echt email adres is, en dat we naar het stuk voor de `@` kunnen kijken voor de `edupersontargetedid`. Het is niet heel erg mooi, maar het zou wel werken.
