### ISSUE TITLE
wij zouden popup bij aanmelden van cursus kunnen tonen

### ISSUE THREAD

**Issue by hermanvand** [SURFnet/learning-analytics#38]
Als iemand op de 'joined-course' pagina komt. Kunnen we met javascript een popup tonen, waarmee we de gebruiker attenderen op het feit dat er gebruik wordt gemaakt van Learning analytics en dat hij zich kan (moet) inschrijven, met een link naar de la-ezperiment pagina's.

Bijkomend voordeel: als iemand met een tweede device komt en die is bij ons niet geregistreerd, dan kunnen we weer de popup tonen!

**Comment by Tjeerd** [comment]
De oplossing hier is afhankelijk van de gebruikte integratie:

Als de JS integratie gebruikt is dan zouden we in ons tracking script een check kunnen doen welke actie werd getracked en dan een simpele alert laten zien. Deze JS zou echter ook aan de client kant geïntegreerd kunnen worden (en kan dan evt in de stijl van de client opgemaakt worden).

Als er geen JS integratie gebruikt is (of mogelijk is) dan zal dit iets van een textuele melding aan de client kant moeten zijn.

**Comment by hermanvand** [comment]
Zou er niet nog een alternatieve oplossing zijn?

Kunnen we bijvoorbeeld niet nog een image laden, die checkt of de gebruiker bekend is, zo ja, dan tonen we een leeg image/1 pixel. Zo niet, dan toen we een image met daarin een button 'Doe mee met Learning Analytics'. De href op de image gaat naar https://la-experiment.surfnet.nl, maar die laten we door de klant zetten, dat kan meestal wel in hun omgeving.

**Comment by Tjeerd** [comment]
Ja, zoiets zou inderdaad wel kunnen ja! Alleen zal de `<a href="">` welke om het plaatje heen moet staan wel binnen het blackboard (oid) gezet worden. Maar dat behoort wellicht wel tot de mogelijkheden, dus de mogelijkheid om een plaatje met een link aan te maken? De `src=""` van het plaatje kunnen we dan naar LA laten verwijzen en dan bepalen of we de gebruiker kennen en vervolgens wel of geen plaatje teruggeven.

**Comment by hermanvand** [comment]
Klopt, de ELO moet dan een plaatje met link kunnen maken. Dat kunnen ze
nog wel :-)


Op 13-12-2016 om 09:37 schreef Tjeerd Bijlsma:

**Comment by Tjeerd** [comment]
Okay, eea is toegevoegd. Let wel, de 'button' is nu groene button met de nederlandse tekst. Mooie toekomstige uitbreiding zou kunnen zijn dat we de image dynamisch genereren, om zo de tekst te kunnen specificeren en de kleur, vorm etc.

**Comment by Tjeerd** [comment]
De url is overigens `/button`
