### ISSUE TITLE
[DESIGN] andere view op homepage / overzicht pagina

### ISSUE THREAD

**Issue by hermanvand** [SURFnet/learning-analytics#39]
de homepage is nu ingedeeld op thema's.
wat ook zou kunnen: indelen op cursussen en dan thema's onder een cursus laten vallen

Kunnen we dan ook 'joined-course' 1 keer doen ipv. 4 keer.

**Comment by rpkamp** [comment]
Hiervoor moeten we het data model aanpassen, omdat er nu inderdaad 1 cursus wordt aangemaakt per thema, dus als een cursus in alle thema's staat dan staan er in de database 4 verschillende cursussen, die wij als mensen zien als 1 omdat ze dezelfde naam hebben.

Dit kunnen we zeker aanpassen zoals gewenst in dit ticket, maar het is niet een kwestie van enkel een template aanpassen, het gaat veel verder dan dat.

**Comment by hermanvand** [comment]
dat vermoeden had ik al, maar het is toch iets wat wel gedaan moet worden. Dit moeten we in het volgende overleg (do 30/3) maar even bespreken. We kunnen 2 kanten op:
- Misschien kunnen we een overkoepelende term verzinnen, die een set course id's zoals we die nu kennen classificeert als één identiteit. 
- Of we herinterpreteren course als iets overkoepelends en de thema's/vragen zijn de elementen ervan.

**Comment by rpkamp** [comment]
we kunnen dit doen door vanaf nu 1 courseId te maken per course waar alle 4 de thema's dan onder getracked worden, en dan voor oude courses die clashen van de clashende courses een alias te maken van de eerdere. 

Als we vervolgens bij het ophalen van de FIMs alle FIMs ophalen van de course, plus al zijn aliassen haal je alle oude data nog op en werken oude trackers ook nog, maar nieuwe trackers kunnen gewoon het overkoepelende courseId gebruiken.

Voor het overzicht betekent dit enkel dat courses die aliases zijn verborgen moeten worden uit het overzicht omdat deze alleen nog maar bestaan voor koppeling, niet meer voor display.

Dus stel er zijn nu de volgende vakken:

CourseId | Name
--- | ---
1 | Programmeren 101
2 | Programmeren 101

Dan zou in de nieuwe situatie vak 2 een alias worden voor vak 1, in tabel vorm zou dat als volgt kunnen weergegeven worden:

CourseId | Name | AliasOf
--- | --- | ---
1 | Programmeren 101 | NULL
2 | Programmeren 101 | 1

Bij het ophalen van de FIM data voor dit vak moet dus niet alleen gekeken worden naar ID 1, maar naar ID 1 en 2. 

In het overzicht van de vakken zou je alleen nog maar vak 1 zien, omdat deze `AliasOf=NULL` heeft.

Het aanmaken van alias zou via de command line kunnen gaan:

```
bin/console la:course:alias <id> <aliasOf>
```

dus voor het specifieke geval hier boven zou het worden

```
bin/console la:course:alias 2 1
```

Automatisch detecteren van aliasen is niet aan te bevelen omdat je dan natuurlijke taal moet matchen en voor de kleine dataset is het de moeite niet waard.

Tot slot zullen URLs aangepast moeten worden van `admin/recipe/1/course/3` naar `admin/course/3/recipe/1` om de structuur van de site beter te reflecteren.

Bovenstaande geldt alleen indien oude data bewaard moet blijven. Indien dat niet hoeft is het slechts een kwestie van even de codebase doorlopen waar het huidige model misloopt, maar waarschijnlijk zijn er weinig aanpassingen nodig.
