### ISSUE TITLE
voortgangsmonitor / control panel / personal course report

### ISSUE THREAD

**Issue by hermanvand** [SURFnet/learning-analytics#41]
Nu moet de docent/student naar de website om de visualisaties te bekijken.

Daarnaast moet er een control panel komen, die in hun eigen leeromgeving bekeken kan worden. Zodat de resultaten makkelijk en snel toegankelijk zijn.

Dit is een samenvatting van de visualisaties op de site. Bijvoorbeeld: Gefeliciteerd! je bent op 37% van de 100%. (Vergelijk je profiel bij linkedin)

**Comment by pablothedude** [comment]
Hiervoor een aparte pagina aangemaakt die als widget kan worden gebruikt met slechts een enkele grafiek om op de leeromgeving te gebruiken.

/widget/course/`courseId`/recipe/`recipeId`/`activityKey`/`verbKey`
/app_dev.php/widget/course/2/recipe/7/course/joined

**Comment by hermanvand** [comment]
Op zich kunnen we hier wel wat mee. Er wordt nu een html snippet getoond, wat we in een iframe kunnen laden. Zie: 

![image](https://user-images.githubusercontent.com/1597455/33551571-0f9fd1d4-d8f2-11e7-9c9f-b6a4521f241e.png)

Er zijn nog 2 aanpassingen nodig:

1. De view is  nu alleen een student view, maar als ik als docent naar mijn pagina's kijk, dan wil ik andere labels. Net zoals op de experiment pagina's zelf.
2. De titel kan eraf ' Gebruik lesmateriaal ...'

**Comment by pablothedude** [comment]
De voorgestelde wijzigingen gedaan en PR klaar gezet

**Comment by hermanvand** [comment]
FIjn, beide aanpassingen zijn gedaan.

het enige dat ik me nog afvraag is of ik nu ingelogd moet zijn in de la-experiment omgeving om dit dashboard te zien. Daar lijkt het wel op nu, en dat klinkt ook logisch.

Zo ja, dan zouden we als ik niet ingelogd ben een linkje moeten tonen met: ' login op de experiment omgeving om het dashboard te zien'. Die link verwijst dan naar de admin dir van de la-experiment server, voor de test is dat: https://test.la-experiment.surfnet.nl/admin/

**Comment by pablothedude** [comment]
Herman bij ons intern krijg ik als ik uitgelogd ben een inlog pagina te zien die middels Simplesaml ingeladen wordt. De vraag van mijn kant is nu dus even wat jullie nu te zien krijgen als er niet ingelogd is? Wordt hier misschien al rekening mee gehoduen via het SSO platform? Zou je hier misschien een screenshot van kunnen maken en even aan dit ticket kunnen hangen dit zodat we mogelijkerwijs niet het wiel opnieuw hoeven uit te vinden.

Als dit nog aangepast moet worden zou dit mogelijkerwijs ook flink wat tijd kunnen kosten omdat er een uitzondering moet worden gemaakt t.o.v. de huidige werking van de applicatie.

**Comment by hermanvand** [comment]
Als ik niet ingelogd ben, dan krijg ik ook de sso login en zie ik dus meteen SURFconext, waar ik mijn instelling moet kiezen.

![niet ingelogde persoon](https://user-images.githubusercontent.com/1597455/34944171-df8fdd8a-f9fe-11e7-8bb9-67baedf4a6b3.png)

**Comment by hermanvand** [comment]
Ik weet even niet wat wenselijk is. Dus laten we dit nu even zo.
mogelijke richtingen zijn:
- accepteren dat iemand moet inloggen (maar dat is wel weer een 'technische'  oplossing)
- het weglaten voor studenten en alleen docenten dit laten zien, hen kunnen we vertellen dat ze ingelogd moeten zijn
- een duidelijke pagina maken, met een link naar een inlog: " hier zou je learning analytics kunnen zien, maar dan moet je even inloggen, klik hier!"

**Comment by hermanvand** [comment]
Voro de volgende release maken we tijd voor optie 3. Kunnen we nu het dashboard alleen tonen voor docenten?

**Comment by hermanvand** [comment]
niet verder getest, maar nemen we mee in 1.3
