### ISSUE TITLE
er zijn meer studenten op een resource geweest dan bij joined course, kan dat?

### ISSUE THREAD

**Issue by hermanvand** [SURFnet/learning-analytics#42]
vraag van hu:

'Kleine vraag over een van de grafieken in het dashboard (zie ook bijlage). In totaal participeren 83 studenten in het experiment. Nou telt de hoeveelheid studenten die een activiteit heeft uitgevoerd overal netjes op tot 83, behalve bij de categorie other resources​. Hier hebben, volgens het dashboard, 88 studenten naar gekeken. Is hier een logische verklaring voor? Misschien studenten die zich hebben ingeschreven maar later weer uitgeschreven (kunnen we dit ergens terugzien?)?'

![la-experiment](https://cloud.githubusercontent.com/assets/1597455/21091974/da6d4b0c-c049-11e6-8210-b26b227dd63a.png)

**Comment by Tjeerd** [comment]
In dit geval is het denk ik gemakkelijk te bepalen door door-te-klikken op de chart en dan te controleren of er ook daadwerkelijk 88 kolommen zijn. Als het er 88 zijn, dan zouden er 5 'vreemde' users tussen moeten zitten. Deze zijn daar dan ook te identificeren. Kan dit helpen om het verschil te verklaren?

**Comment by hermanvand** [comment]
Ja, dat kunnen we doen, maar ik heb geen toegang tot dat account dus kan
dat zelf niet. Dat moet dan samen met de betreffende docent.
