### ISSUE TITLE
aanmaken landingspagina voor windesheim

### ISSUE THREAD

**Issue by hermanvand** [SURFnet/learning-analytics#43]
Voor windesheim kunnen we maken

    url: https://la-experiment.surfnet.nl/windesheim
    naam: Hogeschool Windesheim
    vak: Projecten en kwaliteit in onderwijsorganisaties, fonetische articulatiestoornissen en dyspraxie
    url privacy: geen
    contact: Erik Bolhuis

**Comment by Tjeerd** [comment]
E.e.a. is toegevoegd. Zodra je de vakken weet, geef even een seintje.

**Comment by hermanvand** [comment]
Voor de hva kunnen we maken

url: https://la-experiment.surfnet.nl/hva
naam: Hogeschool van Amsterdam
vak: Programming
url privacy: geen
contact: Jan Hellings

**Comment by Tjeerd** [comment]
Toegevoegd, in het vervolg kunnen de instellingen/vakken e.d. in database aangemaakt worden, tabel `institution`.
