### ISSUE TITLE
[DESIGN]: interface en visualisaties aantrekkelijk maken voor student

### ISSUE THREAD

**Issue by hermanvand** [SURFnet/learning-analytics#55]
inclusief: als student zich aan heeft gemeld, dan komen ze op een pagina waar ze niks kunnen...

Hier moeten we een ontwerp voor maken...

**Comment by hermanvand** [comment]
In groter bespreken

**Comment by pablothedude** [comment]
In afwachting van ontwerp

**Comment by hermanvand** [comment]
Vanochtend hebben we nagedacht over de pagina's voor de student en de verbeteringen hebben we in het bijgevoegd word document staan:

[Ontwerp student pagina 20171114.docx](https://github.com/SURFnet/learning-analytics/files/1470383/Ontwerp.student.pagina.20171114.docx)

**Comment by pablothedude** [comment]
De voorgestelde wijzigingen staan zo goed als allemaal klaar alleen over punt 3 uit het document had ik nog een aantal vragen.

# De activiteit 'joined-course' heb ik nog even laten staan. De vraag is even of het verstandig is om dit nu op te pakken of dat het beter is om het direct met de performance aanpassingen meegenomen kan  worden zodat het nu niet dubbel gebeurd. Is dat een optie?
# Voor de kleur van de grafiek is er de vraag om de kleur rood te gebruiken indien iets nog gedaan moet worden. Wij weten alleen of er iets gedaan is als een tracking pixel in wordt geschoten door een student. Dan pas kunnen we  de koppeling maken tussen een student en een recept. Eerder niet, dus kunnen wij niet bepalen welke studenten nog iets moeten doen, tenzij een leraar ook studenten zou koppelen aan een recept. Herman, hoe zie jij dit?

**Comment by hermanvand** [comment]
wat betreft vraag 1: dat is oke, dat kan ook later

wat betreft vraag 2: 
We weten wel dat iemand iets nog niets heeft gedaan, als andere studenten van hetzelfde vak nl. iets hebben gedaan, dan kun je concluderen dat iemand dit nog niet heeft gedaan. Vandaar de naam FIM, dat staat voor 'full information matrix' en  in die tabel zou dit bekend (moeten) zijn.
Als Niemand van de cursus een bepaalde leeractiviteit heeft gedaan, dan wordt een grafiek aan Niemand getoond. Zodra er 1 student is die een leeractiviteit heeft uitgevoerd, dan kan de grafiek bij ALLE studenten (van de betreffende cursus) getoond worden. En dat laatste is precies dit rode vlak.

**Comment by hermanvand** [comment]
In het overzicht willen we graag alleen blauwe knoppen (bekijk resultaten) zien, als er ook echt resultaten zijn. Dat geldt voor ' gebruik lesmateriaal'  en ' formatief toetsen'  in ons geval. De andere mogen leeg blijven.

![blauwe knoppen](https://user-images.githubusercontent.com/1597455/34945325-3cba5b62-fa03-11e7-96c9-2dc57a6b476e.png)

**Comment by pablothedude** [comment]
Over de voortgang heb ik nog wel een vraag. Ik denk dat er aan mijn kant wat verwarring is ontstaan vanwege de requirement om voortgang weer te geven van zaken die ze 'nog niet' hebben gedaan.

De koppeling van een student met een cursus kunnen we inderdaad maken. Maar dit kan zoals je aangeeft pas op het moment dat er een activiteit is gedaan voor een cursus (en iemand voorkomt in de FIM-tabel). We kunnen dus pas de voortgang bepalen als iemand een keer voorkomt in de FIM-tabel voor een bepaalde cursus en eerder niet.

Dat we dit dan pas kunnen vanaf dat moment is dus verder geen probleem?

**Comment by hermanvand** [comment]
Klopt, daar kunnen we verder niets aan doen. We weten niet van te voren wat we gaan meten, maar als iets voorkomt in de tabel, dan proberen we wel zoveel mogelijk informatie te achterhalen.

**Comment by pablothedude** [comment]
### 1. Voortgang
Voor de kleur van de grafiek heb ik nog even gekeken en er is relatief veel logica binnen de huidige opzet die ervoor zorgt dat het lastig voor elkaar te krijgen is. Dit komt omdat er nu geen verschil zit tussen 0 interacties in de grafieken en dat dit nu wel zal moeten om inzichtelijk te krijgen of iets moet gebeuren. Het gaat dan om het verschil tussen geen interacties (maar moet nog wel gebeuren) en geen interacties (en hoeft ook niet te gebeuren).

Ik heb hier ook nog even met Tjeerd naar gekeken en we denken dat het toch de beste optie is om e.e.a. uit elkaar te trekken op het moment dat de performance aanpassingen door worden gevoerd, Op dit moment kan ik namelijk wel een laag bovenop de huidige logica bouwen maar dan ben ik bang dat we dit na de performance wijzigingen opnieuw moeten doen of dat die wijzigingen meer tijd gaan kosten om met deze aanpassingen rekening te kunnen houden. Dan kunnen er ook direct even goede tests worden op gezet voor de grafieken om ook te kunnen blijven valideren dat alles naar behoren werkt.

### 2. Knoppen verbergen
Dit kan ik niet reproduceren, bij mij lokaal worden de resultaten ook niet getoond als er geen resultaten zijn in de fim tabel. Zou je misschien eens willen kijken wat er uit deze query komt:
```SELECT DISTINCT r0_.id AS id_0 FROM recipe r0_ INNER JOIN fim f1_ ON (r0_.id = f1_.recipe AND f1_.course = ?) WHERE f1_.email = ?```
Waarbij de eerste vraagteken de id van de betreffende cours eis en de email het emailadres van de betreffende user met `mailto:` ervoor.

**Comment by hermanvand** [comment]
wat betreft 1: jammer van de aanpassing van de grafiek. Ik denk dat het nu belangrijk is om toe te werken naar een nieuwe versie. Laten we dit daarom maar meenemen naar de volgende ronde dan. ik noteer het.

wat betreft de query, het resultaat is:

+------+
| id_0 |
+------+
|    1 |
|    2 |
|    3 |
|    4 |
+------+
4 rows in set (0.00 sec)

**Comment by pablothedude** [comment]
#2 Vreemd, dat de query toch alle recepten terug geeft, dat zou dan moeten betekenen dat er toch interacties in de fim tabel staan. Kan je toevallig zien wat er terug komt. Dan kunnen we even bepalen wat hier dan verder mee zou moeten gebeuren?

**Comment by pablothedude** [comment]
De knoppen werden altijd getoond omdat de Course/Joined actie op alle recipes wordt geregistreerd en dit er dus gelijk voor zorgde dat alle buttons zichtbaar werden. Deze actie uit de query gehaald.

**Comment by hermanvand** [comment]
werkt nu op produktie bij SURFsara
