### ISSUE TITLE
[RECEPTEN]: bij de grafieken het aantal studenten toen, zodat je weet waar de grafiek over gaat

### ISSUE THREAD

**Issue by hermanvand** [SURFnet/learning-analytics#59]
Het betreft de grafieken waar het gebruik van de objecten worden geplot (de onderste drie opties in de interface) en waar niet het totaal gelijk is aan 100% van de studenten. 

Je ziet bijvoorbeeld dat er 60x joined-course is geactiveerd. Maar daar zie je dan niet bij door heveel studenten dat is gedaan.

**Comment by hermanvand** [comment]
Even met Ilja overleggen of dit nog steeds gewenst is, als de drilldown is geimplementeerd

**Comment by rpkamp** [comment]
Uit overleg met Ilja kwam dat dit inderdaad nog steeds gewenst is.
