### ISSUE TITLE
Join course 1 keer per course in plaats van 1 keer per recept

### ISSUE THREAD

**Issue by rpkamp** [SURFnet/learning-analytics#94]
Op dit moment is voor object "course" en verb "join" nodig dat dit 1 keer per mogelijk recept gedaan moet worden. Het zou goed zijn een oplossing te vinden waarbij dit niet meer nodig is en een join course geldt voor de volledige course met alle recepten die daar onder vallen.

**Comment by pablothedude** [comment]
Hiervoor een aanpassing gedaan zodat het nu mogelijk is om meerdere recipe id's in het tracking pixel request mee te sturen. Dit kan door de id's te scheiden door een pipeline `|`. Bij het maken van de tracking recipes wordt dit in het geval van course/joined nu ook gedaan:
`https://dev.la.org/app_dev.php/track?recipe=5|6|7|8&verb=joined&object=course&course=2&label=[label]&`

**Comment by hermanvand** [comment]
Ik kan op de test omgeving het /track commando niet testen, vanwege een 500 error.

zie url: https://test.la-experiment.surfnet.nl/track?recipe=4&verb=accessed&object=other&course=3&label=eerste%20pagina&week=week%201&subject=test%201&

De volgende foutmelding verschijnt in prod.log:

[2017-12-04 12:17:10] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "Assert" from namespace "Webmozart\Assert". Did you forget a "use" statement for "Assert\Assert"?" at /var/www/learning-analytics/releases/20171204100626/src/AppBundle/Assembler/TrackCommandAssembler.php line 20 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"Assert\" from namespace \"Webmozart\\Assert\".\nDid you forget a \"use\" statement for \"Assert\\Assert\"? at /var/www/learning-analytics/releases/20171204100626/src/AppBundle/Assembler/TrackCommandAssembler.php:20)"} []

**Comment by pablothedude** [comment]
Dit kan ik zelf niet reproduceren. Ik heb wel  even een aanpassing gedaan die @rpkamp ook had gedaan om te kijken of dit het beoogde resultaat geeft. Zou je misschien kunnen valideren of dit werkt?

**Comment by hermanvand** [comment]
Welke aanpassing moet ik installeren om dit te testen? btw: ik probeer het nog even tussendoor te doen, maar waarschijnlijk wordt het maandag pas.

**Comment by hermanvand** [comment]
Oke, ik kan nu wel testen en het werkt ook deels.

Ik zie dat er nu een tracker naar de server wordt gestuurd.
- op de overzicht pagina wordt nu voor ieder thema de groene 'knop' met ' 1student' getoond.

Wat niet gebeurd:
- er staat niet onder ieder thema een joined-course grafiek. De vraag is of er wel voor ieder recept nu ook in de lrs een statement wordt geplaatst?

**Comment by pablothedude** [comment]
Dit zou moeten gebeuren als je ingelogd bent als leerling en je emailadres bekend is. Als hij wel in de usage tabel staat maar niet bij LRS uit komt is het waarschijnlijk dat je admin bent (ROLE_ADMIN). Dan zal dit inderdaad niet werken omdat hij alleen acties van studenten tracked.

Zou je even kunnen kijken of dit het geval is?

**Comment by hermanvand** [comment]
We zien wel dat er nu 4 statements in de lrs worden gezet. In de interface wordt alleen de joined-course grafiek getoond als er ook een andere grafiek getoond wordt. Dat is in ons geval bij recept 3 en 4.

Kan het zijn dat de course-joined grafiek dus niet op zichzelf kan worden getoond, bij ons hebben recept 1 en 2 nog geen ander grafieken (en dus ook niet joined-course).

**Comment by hermanvand** [comment]
deze kunnen we dus sluiten
